# GET http://localhost:3000/

# POST http://localhost:3000/send
# Content-Type: application/json

# {
#   "phoneNumber" : "+918950406539"
# }

# POST http://localhost:3000/orders/cancel/64ae92bf8a2554ed9c43d7aa
# Content-Type: application/json

# {
  
# }

POST http://localhost:3000/add_product
Content-Type: application/json

{
    
}

#  GET http://localhost:3000/verify?email=rdrishi97@gmail.com&token=148555
