# GET http://localhost:3000/

# POST http://localhost:3000/send
# Content-Type: application/json

# {
#   "phoneNumber" : "+918950406539"
# }

POST http://localhost:3000/signup
Content-Type: application/json

{
   "name" : "Rishi",
   "email" : "rishidhingra04@gmail.com",
   "password" : "Talanted@123"
}

# POST http://localhost:3000/api/payments/verify
# Content-Type: application/json

# {
#     "orderId": "310466636V337452L"
# }

#  GET http://localhost:3000/verify?email=rdrishi97@gmail.com&token=148555
